//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dall
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class expedientes_jbjEntities : DbContext
    {
        public expedientes_jbjEntities()
            : base("name=expedientes_jbjEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<adj_consultas> adj_consultas { get; set; }
        public DbSet<asignacion> asignacions { get; set; }
        public DbSet<consulta> consultas { get; set; }
        public DbSet<contraparte> contrapartes { get; set; }
        public DbSet<detalle_consulta> detalle_consulta { get; set; }
        public DbSet<expediente> expedientes { get; set; }
        public DbSet<gestion> gestions { get; set; }
        public DbSet<honorario> honorarios { get; set; }
        public DbSet<juicio> juicios { get; set; }
        public DbSet<sujeto> sujetos { get; set; }
        public DbSet<usuario> usuarios { get; set; }
        public DbSet<demanda> demandas { get; set; }
        public DbSet<notariado> notariadoes { get; set; }
    
        public virtual ObjectResult<buscarxfechas_Result> buscarxfechas(Nullable<System.DateTime> fi, Nullable<System.DateTime> ff)
        {
            var fiParameter = fi.HasValue ?
                new ObjectParameter("fi", fi) :
                new ObjectParameter("fi", typeof(System.DateTime));
    
            var ffParameter = ff.HasValue ?
                new ObjectParameter("ff", ff) :
                new ObjectParameter("ff", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscarxfechas_Result>("buscarxfechas", fiParameter, ffParameter);
        }
    }
}
